app_name: mentions2tasks
pm_tool:  redbooth
filename: settings

twitter:
  owner:                screen_name
  owner_id:             twitter_id
  api_key:              twitter_api_key
  api_secret:           twitter_api_secret
  access_token:         twitter_access_token
  access_token_secret:  twitter_access_token_secret
  access_level:         Read-only

project_management_app:
  redbooth:
    client_id:      md5clientidhash
    client_secret:  md5clientsecrethash
    login_url:      https://redbooth.com/session
    authorize_url:  https://redbooth.com/oauth2/authorize
    token_url:      https://redbooth.com/oauth2/token
    redirect_uri:   http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fredbooth%2Fcallback
    project_id:     123456
    tasklist_id:    654321


