app:
  app_name:                 mentions2tasks
  file_name:                settings
  http_base:                http://somewhere.com:3000
  project_management_tool:  redbooth

apps:

  twitter:
    auth:
      access_token:         ACCESS_TOKEN
      access_token_secret:  ACCESS_TOKEN_SECRET
      access_level:         Read-only
      path:
        access_token:       /oauth/access_token
        app_only_auth:      /oauth2/token
        authorize:          /oauth/authorize
        request_token:      /oauth/request_token
    http_base:              https://api.twitter.com
    user:
      owner:                OWNER
      owner_id:             OWNER_ID
      api_key:              API_KEY
      api_secret:           API_SECRET

  redbooth:
    auth:
      client_id:            CLIENT_ID
      client_secret:        CLIENT_SECRET
      path:
        authorize:          /oauth2/authorize
        auth_token:         /oauth2/token
        auth_callback:      /oauth/redbooth/callback
        refresh_token:      /oauth2/token
        refresh_callback:   /oauth2/refresh/redbooth/cal
    http_base:              https://redbooth.com
    user:
      id:             0
      project_id:     0
      task_list_id:   0
