app_name: mentions2tasks
pm_tool:  redbooth
filename: settings

twitter:
  owner:                screen_name
  owner_id:             twitter_id
  api_key:              twitter_api_key
  api_secret:           twitter_api_secret
  access_token:         twitter_access_token
  access_token_secret:  twitter_access_token_secret
  access_level:         Read-only
  urls:
    app_only_auth:  https://api.twitter.com/oauth2/token
    request_token:  https://api.twitter.com/oauth/request_token
    authorize:      https://api.twitter.com/oauth/authorize
    access_token:   https://api.twitter.com/oauth/access_token


project_management_app:
  redbooth:
    client_id:      md5clientidhash
    client_secret:  md5clientsecrethash
    authorize_url:  https://redbooth.com/oauth2/authorize
    token_url:      https://redbooth.com/oauth2/token
    redirect_uri:   http://localhost:3000/oauth/redbooth/callback
    project_id:     123456
    tasklist_id:    654321


