twitter:
  owner:                screen_name
  owner_id:             twitter_id
  app_name:             twitter_app_name
  api_key:              twitter_api_key
  api_secret:           twitter_api_secret
  access_token:         twitter_access_token
  access_token_secret:  twitter_access_token_secret
  access_level:         Read-only

project_management_app:
  redbooth:
    user_name:      somebody@somewhere.com
    password:       123456
    client_id:      md5clientidhash
    client_secret:  md5clientsecrethash
    authorize_url:  https://redbooth.com/oauth2/authorize
    token_url:      https://redbooth.com/oauth2/token
    cookie_name:    name_of_auth_cookie
    redirect_uri:   https%3A%2F%2Flocalhost%3A3000%2Foauth_tool%2Fcallback
    project_id:     123456
    tasklist_id:    654321


