app:
  app_name:                 mentions2tasks
  file_name:                production.local
  http_base:                http://mentions2tasks.herokuapp.com

apps:

  twitter:
    auth:
      access_token:         <%= ENV['TWITTER_ACCESS_TOKEN'] %>
      access_token_secret:  <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
      access_level:         Read-only
    user:
      owner:                <%= ENV['TWITTER_OWNER_NAME'] %>
      owner_id:             <%= ENV['TWITTER_OWNER_ID'] %>
      api_key:              <%= ENV['TWITTER_API_KEY'] %>
      api_secret:           <%= ENV['TWITTER_API_SECRET'] %>

  redbooth:
    auth:
      client_id:            <%= ENV['REDBOOTH_CLIENT_ID'] %>
      client_secret:        <%= ENV['REDBOOTH_CLIENT_SECRET'] %>
    user:
      id:                   <%= ENV['REDBOOTH_USER_ID'] %>
      project_id:           <%= ENV['REDBOOTH_USER_PROJECT_ID'] %>
      task_list_id:         <%= ENV['REDBOOTH_USER_TASKLIST_ID'] %>